//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlimSatimSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        public int Id { get; set; }
        public string Detay { get; set; }
        public string Tutar { get; set; }
        public string KalanTutar { get; set; }
        public string BirimFiyat { get; set; }
        public Nullable<System.DateTime> IslemZamani { get; set; }
    }
}
